### ISSUE TITLE
Configurations issues

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#39]
### Because

Issue to keep track of configuration decisions and questions.

We decided to have two configuration files: one with settings for the model and one with run-time parameters.

The example configuration file [modeling/config/classifier-full.yaml](https://github.com/clamsproject/app-swt-detection/blob/refactor-feat-extractor/modeling/config/classifier-full.yml) has both of them (for now), including some settings for binning:

```yaml
prebin: 
  - bars
  - slate
  - chyron
  - text-not-chyron
  - person-not-chyron
  - credit
  - other
labels: [ "slate", "chyron", "credit", "other" ]
postbin:
  0: 3
  1: 0
  2: 1
  3: 3
  4: 3
  5: 2
  6: 3
```

Currently, the train code just generates (this is for a different model, but the idea should be clear):

```yaml
bins: {'pre': {'slate': ['S'], 'chyron': ['I', 'N', 'Y'], 'credit': ['C']}, 'post': {'sladit': ['slate', 'credit'], 'chyron': ['chyron']}}
labels: ['sladit', 'chyron', 'other']
```

The question is which format we prefer for the config file. I would prefer something like

```yaml
labels:
  - sladit
  - chyron
  - other
bins:
  - sladit
    - slate
    - credit
  - chryon
    - chyron
  - other
```
 Or even

```yaml
labels:
  - sladit
    - slate
    - credit
  - chryon
    - chyron
  - other
```

It is compact yet has all the information needed, I might be wrong about the latter though.

I am also somewhat uncomfortable with the "other" label.
