### ISSUE TITLE
Labels are wrongly associated with scores

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#43]
### Because

Somewhere along the line we started assigning the wrong label, probably because the way we dealt with configurations has changed several times.

The config file `modeling/config/trainer.yml` has:

```yaml
bins:
  pre:
    slate:
      - "S"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"
```

And the classifier config in `/modeling/models/20231214-193543.convnext_tiny.kfold_config.yml` has

```yaml
labels:
- slate
- chyron
- credit
```

But the method `train.get_final_label_names()` returns

```python
['chyron', 'credit', 'slate', 'NEG']
```

and since that method is eventually used to set labels on an instance of Prediction we get a mismatch.

**Comment by marcverhagen** [comment]
This was fixed in https://github.com/clamsproject/app-swt-detection/commit/71b57a224438969aa1116a25ef6d8b0a103d6a1f by using the labels field from the model config file. An alternative would be to change

```yaml
bins:
  pre:
    slate:
      - "S"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"
 ```
into

```
bins:
  pre:
    - slate:
      - "S"
    - chyron:
      - "I"
      - "N"
      - "Y"
    - credit:
      - "C"
```

and update `train.get_final_label_names()`.
